### ISSUE TITLE
C++ compiler has not been specified

### ISSUE THREAD

**Issue by SG7** [filcuc/nanomsg-multi-client-server-example#2]
Thank you for nice nanomsg-multi-client-example!

I am trying to compile the project with CLion on Linux Red Hat 7.2
Unfortunately due to some C++14 features compilations fails.

Could you give some compilation instructions and specify the compiler which you used/can be used to compile the project? Thanks!

**Comment by filcuc** [comment]
@SG7 thank you. I'm using archlinux with gcc 6.2.1 so it's pretty recent.
If you can post me your error i can help you further.
Given that any compiler who implement c++14 should work

**Comment by SG7** [comment]
Thank you @filcuc for relaxing the requirements to C++11! Now, most of the older compilers should compile.
Regarding the error I had the problem with:  
`connection = std::make_unique<Connection>(socket_id, url, Connection::Type::Connect);`
